version: 2.1.0
atlas_user: "zealic"

variables:
  default: {
    "headless": "false",
    "iso_url": "https://mirrors.ustc.edu.cn/centos/7/isos/x86_64/CentOS-7-x86_64-NetInstall-1503.iso",
    "iso_checksum": "111379a06402e1e445c6aeee9401d031",
    "iso_checksum_type": "md5",
    "mirror_host": "mirrors.ustc.edu.cn"
  }
  push: {
    "headless": "true",
    "iso_url": "http://mirrors.kernel.org/centos/7/isos/x86_64/CentOS-7-x86_64-NetInstall-1503.iso",
    "iso_checksum": "111379a06402e1e445c6aeee9401d031",
    "iso_checksum_type": "md5",
    "mirror_host": "mirrors.kernel.org"
  }

remote-shell:
  # System Base
  - [
      "scripts/packages.sh",
      "scripts/docker.sh",
      "scripts/vagrant.sh"
    ]
  # Languages
  - [
      "scripts/lang/golang.sh",
      "scripts/lang/nodejs.sh",
      "scripts/lang/python.sh",
      "scripts/lang/ruby.sh"
    ]
  # Docker images
  - [
      "scripts/docker/general.sh"
    ]
  # Cloud
  - "scripts/cloud-init.sh"
  # Virtual Macine required
  - "scripts/vm-tools.sh"
  # Fuck GFW
  - "scripts/fuck_gfw.sh"
  # Cleanup
  - "scripts/cleanup.sh"
